name: Build MindTheGapps

on:
  workflow_dispatch:
    inputs:
      androidv:
        description: 'Android Version'
        required: true
        default: '16.0.0'
        type: choice
        options:
          - '16.0.0'
          - '17.0.0'
      release:
        description: "Release"
        required: true
        default: false
        type: boolean
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        arch: ["x86_64"]
        androidv: ${{ fromJSON( github.event_name == 'schedule' && '["16.0.0", "17.0.0"]' || format('["{0}"]', inputs.androidv) ) }}
    name: Build ${{ matrix.androidv }}-${{ matrix.arch }}
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Map version to tree
        run: |
          declare -A ANDROID_VER_MAP=(["16.0.0"]="baklava" ["17.0.0"]="cinnamonbun")
          echo "ANDROIDV=${ANDROID_VER_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV
          declare -A ANDROID_API_MAP=(["16.0.0"]=36 ["17.0.0"]=37)
          echo "ANDROID_API=${ANDROID_API_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV

      - name: Clone repository
        run: |
          git config --global http.version HTTP/1.1
          git clone --depth=1 -b ${{ env.ANDROIDV }} https://github.com/tling0001/vendor_gapps.git/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Build
        working-directory: vendor_gapps
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          make gapps_x86_64

      - name: Rename Outputs
        working-directory: vendor_gapps/out
        run: |
          for f in *.*; do
            mv "$f" "MindTheGapps-${{ matrix.androidv }}-${{ matrix.arch }}-${{ env.date }}.${f##*.}"
          done

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: vendor_gapps/out/MindTheGapps-*.*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MindTheGapps-${{ matrix.androidv }}-${{ matrix.arch }}-${{ env.date }}
          path: vendor_gapps/out/*.*
          if-no-files-found: warn
          compression-level: 0

      - name: Release
        uses: softprops/action-gh-release@v2
        if: inputs.release == true || github.event_name == 'schedule'
        with:
          tag_name: ${{ env.date }}
          draft: false
          prerelease: false
          files: vendor_gapps/out/*.*
